"""Add date_registered and last_login to User model

Revision ID: 1002038f7807
Revises: e35cb889fbe0
Create Date: 2024-12-08 23:11:35.782972

"""
from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '1002038f7807'
down_revision = 'e35cb889fbe0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('date_registered')
    # ### end Alembic commands ###